name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PIP Modules
      run: python -m pip install -r requirements.txt

    - name: Build Project (Dynamic build)
      if: matrix.os == 'windows-latest'
      run: pyinstaller --noconsole --name="Twitch Plays Corporate Clash" --add-data "assets/*;assets/" --distpath=dynamic --icon="assets/flippyHead.ico" main.py

    - name: Build Project (Static build)
      if: matrix.os == 'windows-latest'
      run: pyinstaller --onefile --noconsole --name="Twitch Plays Corporate Clash" --add-data "assets/*;assets/" --icon="assets/flippyHead.ico" main.py

    - name: Build Project (macOS build)
      if: matrix.os == 'macos-latest'
      run: pyinstaller --onefile --noconsole --name="Twitch Plays Corporate Clash" --add-data "assets/*:assets/" --icon="assets/flippyHead.ico" main.py

    - name: Purge Files (macOS build)
      if: matrix.os == 'macos-latest'
      run: cd "/Users/runner/work/Twitch-Plays-Corporate-Clash/Twitch-Plays-Corporate-Clash/dist/" && rm "Twitch Plays Corporate Clash"

    - name: Upload Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MarioPartyToolkit-win32-static
        path: D:\a\Twitch-Plays-Corporate-Clash\Twitch-Plays-Corporate-Clash\dist

    - name: Upload Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MarioPartyToolkit-win32-dynamic
        path: D:\a\Twitch-Plays-Corporate-Clash\Twitch-Plays-Corporate-Clash\dynamic

    - name: Upload Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MarioPartyToolkit-darwin
        path: /Users/runner/work/Twitch-Plays-Corporate-Clash/Twitch-Plays-Corporate-Clash/dist
